#!/bin/bash
FILES=./design/ddoc-*.js

push='./node_modules/couchapp/bin.js push'
couch="http://$COUCHDB_USERNAME:$COUCHDB_PASSWORD@localhost:5984/cee_portfolio"

if [[ $* == *all* ]]
then
  for f in $FILES
  do
    echo "Uploading $f file..."
    $push $f $couch
  done
  echo 'Uploading app.js file...'
  $push app.js $couch
fi

if [[ -z $* ]]
then
  echo 'ERROR: No arguments given.'
  exit 1
fi

if [[ $* == *app* ]]
then
  echo 'Uploading app.js file...'
  $push app.js $couch
fi

if [[ $* == *grades* ]]
then
  echo 'Uploading grades.js file...'
  $push ./design/ddoc-grades.js $couch
fi

if [[ $* == *publications* ]]
then
  echo 'Uploading publications.js file...'
  $push ./design/ddoc-publications.js $couch
fi

if [[ $* == *standards* ]]
then
  echo 'Uploading standards.js file...'
  $push ./design/ddoc-standards.js $couch
fi

if [[ $* == *cc* ]]
then
  echo 'Uploading common-core.js file...'
  $push ./design/ddoc-common-core.js $couch
fi

if [[ $* == *lessons* ]]
then
  echo 'Uploading lessons.js file...'
  $push ./design/ddoc-lessons.js $couch
fi